name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      run: |
          npm cache clean --force
          npm i
          node ./node_modules/@angular/cli/bin/ng build --prod --outputPath=dist --base-href=https://zyxbest.github.io/angular-demo/

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.

    # - name: Build and Deploy
    #   uses: JamesIves/github-pages-deploy-action@v4.2.2
    #   env:
    #     ACCESS_TOKEN: ${{ secrets.access_token }}
    #     BRANCH: gh-pages
    #     FOLDER: build
    #     BUILD_SCRIPT: npm install && npm run build
